language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.0
    - android-22
    - sys-img-armabi-v7a-android-22
    - sys-img-x86-android-22
script: gradle assembleDebug
